// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package db

import (
	"context"
	"database/sql"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (id, actor_type, actor_id, event_type, entity_type, entity_id, metadata_json)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAuditLogParams struct {
	ID           string         `json:"id"`
	ActorType    sql.NullString `json:"actor_type"`
	ActorID      sql.NullString `json:"actor_id"`
	EventType    string         `json:"event_type"`
	EntityType   sql.NullString `json:"entity_type"`
	EntityID     sql.NullString `json:"entity_id"`
	MetadataJson sql.NullString `json:"metadata_json"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog,
		arg.ID,
		arg.ActorType,
		arg.ActorID,
		arg.EventType,
		arg.EntityType,
		arg.EntityID,
		arg.MetadataJson,
	)
	return err
}

const listAuditLogsByActor = `-- name: ListAuditLogsByActor :many
SELECT id, actor_type, actor_id, event_type, entity_type, entity_id, metadata_json, created_at
FROM audit_logs
WHERE actor_type = ? AND actor_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAuditLogsByActorParams struct {
	ActorType sql.NullString `json:"actor_type"`
	ActorID   sql.NullString `json:"actor_id"`
	Limit     int64          `json:"limit"`
	Offset    int64          `json:"offset"`
}

func (q *Queries) ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByActor,
		arg.ActorType,
		arg.ActorID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorType,
			&i.ActorID,
			&i.EventType,
			&i.EntityType,
			&i.EntityID,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByEventType = `-- name: ListAuditLogsByEventType :many
SELECT id, actor_type, actor_id, event_type, entity_type, entity_id, metadata_json, created_at
FROM audit_logs
WHERE event_type = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAuditLogsByEventTypeParams struct {
	EventType string `json:"event_type"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

func (q *Queries) ListAuditLogsByEventType(ctx context.Context, arg ListAuditLogsByEventTypeParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByEventType, arg.EventType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorType,
			&i.ActorID,
			&i.EventType,
			&i.EntityType,
			&i.EntityID,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
