// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client_upload_permissions.sql

package db

import (
	"context"
)

const createClientUploadPermission = `-- name: CreateClientUploadPermission :exec
INSERT INTO client_upload_permissions (id, owner_type, owner_id, target_type, target_id)
VALUES (?, ?, ?, ?, ?)
`

type CreateClientUploadPermissionParams struct {
	ID         string `json:"id"`
	OwnerType  string `json:"owner_type"`
	OwnerID    string `json:"owner_id"`
	TargetType string `json:"target_type"`
	TargetID   string `json:"target_id"`
}

func (q *Queries) CreateClientUploadPermission(ctx context.Context, arg CreateClientUploadPermissionParams) error {
	_, err := q.db.ExecContext(ctx, createClientUploadPermission,
		arg.ID,
		arg.OwnerType,
		arg.OwnerID,
		arg.TargetType,
		arg.TargetID,
	)
	return err
}

const deleteClientUploadPermission = `-- name: DeleteClientUploadPermission :exec
DELETE FROM client_upload_permissions
WHERE id = ?
`

func (q *Queries) DeleteClientUploadPermission(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteClientUploadPermission, id)
	return err
}

const listClientUploadPermissionsByOwner = `-- name: ListClientUploadPermissionsByOwner :many
SELECT id, owner_type, owner_id, target_type, target_id, created_at
FROM client_upload_permissions
WHERE owner_type = ? AND owner_id = ?
ORDER BY created_at DESC
`

type ListClientUploadPermissionsByOwnerParams struct {
	OwnerType string `json:"owner_type"`
	OwnerID   string `json:"owner_id"`
}

func (q *Queries) ListClientUploadPermissionsByOwner(ctx context.Context, arg ListClientUploadPermissionsByOwnerParams) ([]ClientUploadPermission, error) {
	rows, err := q.db.QueryContext(ctx, listClientUploadPermissionsByOwner, arg.OwnerType, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientUploadPermission
	for rows.Next() {
		var i ClientUploadPermission
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.OwnerID,
			&i.TargetType,
			&i.TargetID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
