// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: clients.sql

package db

import (
	"context"
	"database/sql"
)

const createClient = `-- name: CreateClient :exec
INSERT INTO clients (id, email, display_name, password_hash, can_upload, is_active)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateClientParams struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	DisplayName  string         `json:"display_name"`
	PasswordHash sql.NullString `json:"password_hash"`
	CanUpload    int64          `json:"can_upload"`
	IsActive     int64          `json:"is_active"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) error {
	_, err := q.db.ExecContext(ctx, createClient,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.CanUpload,
		arg.IsActive,
	)
	return err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients
WHERE id = ?
`

func (q *Queries) DeleteClient(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteClient, id)
	return err
}

const getClientByEmail = `-- name: GetClientByEmail :one
SELECT id, email, display_name, password_hash, can_upload, is_active, created_at, updated_at
FROM clients
WHERE email = ?
`

func (q *Queries) GetClientByEmail(ctx context.Context, email string) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByEmail, email)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CanUpload,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, email, display_name, password_hash, can_upload, is_active, created_at, updated_at
FROM clients
WHERE id = ?
`

func (q *Queries) GetClientByID(ctx context.Context, id string) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CanUpload,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, email, display_name, password_hash, can_upload, is_active, created_at, updated_at
FROM clients
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListClientsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.PasswordHash,
			&i.CanUpload,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :exec
UPDATE clients
SET display_name = ?,
    can_upload = ?,
    is_active = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateClientParams struct {
	DisplayName string `json:"display_name"`
	CanUpload   int64  `json:"can_upload"`
	IsActive    int64  `json:"is_active"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) error {
	_, err := q.db.ExecContext(ctx, updateClient,
		arg.DisplayName,
		arg.CanUpload,
		arg.IsActive,
		arg.ID,
	)
	return err
}
