// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: client_groups.sql

package db

import (
	"context"
	"database/sql"
)

const addClientToGroup = `-- name: AddClientToGroup :exec
INSERT INTO client_group_members (client_group_id, client_id)
VALUES (?, ?)
`

type AddClientToGroupParams struct {
	ClientGroupID string `json:"client_group_id"`
	ClientID      string `json:"client_id"`
}

func (q *Queries) AddClientToGroup(ctx context.Context, arg AddClientToGroupParams) error {
	_, err := q.db.ExecContext(ctx, addClientToGroup, arg.ClientGroupID, arg.ClientID)
	return err
}

const createClientGroup = `-- name: CreateClientGroup :exec
INSERT INTO client_groups (id, name, created_by_user_id)
VALUES (?, ?, ?)
`

type CreateClientGroupParams struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	CreatedByUserID sql.NullString `json:"created_by_user_id"`
}

func (q *Queries) CreateClientGroup(ctx context.Context, arg CreateClientGroupParams) error {
	_, err := q.db.ExecContext(ctx, createClientGroup, arg.ID, arg.Name, arg.CreatedByUserID)
	return err
}

const deleteClientGroup = `-- name: DeleteClientGroup :exec
DELETE FROM client_groups
WHERE id = ?
`

func (q *Queries) DeleteClientGroup(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteClientGroup, id)
	return err
}

const getClientGroupByID = `-- name: GetClientGroupByID :one
SELECT id, name, created_by_user_id, created_at
FROM client_groups
WHERE id = ?
`

func (q *Queries) GetClientGroupByID(ctx context.Context, id string) (ClientGroup, error) {
	row := q.db.QueryRowContext(ctx, getClientGroupByID, id)
	var i ClientGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listClientGroups = `-- name: ListClientGroups :many
SELECT id, name, created_by_user_id, created_at
FROM client_groups
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListClientGroupsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListClientGroups(ctx context.Context, arg ListClientGroupsParams) ([]ClientGroup, error) {
	rows, err := q.db.QueryContext(ctx, listClientGroups, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientGroup
	for rows.Next() {
		var i ClientGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupClients = `-- name: ListGroupClients :many
SELECT c.id, c.email, c.display_name, c.password_hash, c.can_upload, c.is_active, c.created_at, c.updated_at
FROM clients c
JOIN client_group_members cgm ON cgm.client_id = c.id
WHERE cgm.client_group_id = ?
ORDER BY c.created_at DESC
`

func (q *Queries) ListGroupClients(ctx context.Context, clientGroupID string) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listGroupClients, clientGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.PasswordHash,
			&i.CanUpload,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeClientFromGroup = `-- name: RemoveClientFromGroup :exec
DELETE FROM client_group_members
WHERE client_group_id = ? AND client_id = ?
`

type RemoveClientFromGroupParams struct {
	ClientGroupID string `json:"client_group_id"`
	ClientID      string `json:"client_id"`
}

func (q *Queries) RemoveClientFromGroup(ctx context.Context, arg RemoveClientFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, removeClientFromGroup, arg.ClientGroupID, arg.ClientID)
	return err
}

const updateClientGroup = `-- name: UpdateClientGroup :exec
UPDATE client_groups
SET name = ?
WHERE id = ?
`

type UpdateClientGroupParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateClientGroup(ctx context.Context, arg UpdateClientGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateClientGroup, arg.Name, arg.ID)
	return err
}
