// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_events.sql

package db

import (
	"context"
	"database/sql"
)

const createEmailEvent = `-- name: CreateEmailEvent :exec
INSERT INTO email_events (id, event_type, recipient_email, provider_message_id, status, error_text, payload_json)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateEmailEventParams struct {
	ID                string         `json:"id"`
	EventType         string         `json:"event_type"`
	RecipientEmail    string         `json:"recipient_email"`
	ProviderMessageID sql.NullString `json:"provider_message_id"`
	Status            string         `json:"status"`
	ErrorText         sql.NullString `json:"error_text"`
	PayloadJson       sql.NullString `json:"payload_json"`
}

func (q *Queries) CreateEmailEvent(ctx context.Context, arg CreateEmailEventParams) error {
	_, err := q.db.ExecContext(ctx, createEmailEvent,
		arg.ID,
		arg.EventType,
		arg.RecipientEmail,
		arg.ProviderMessageID,
		arg.Status,
		arg.ErrorText,
		arg.PayloadJson,
	)
	return err
}

const listEmailEventsByStatus = `-- name: ListEmailEventsByStatus :many
SELECT id, event_type, recipient_email, provider_message_id, status, error_text, payload_json, created_at
FROM email_events
WHERE status = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListEmailEventsByStatusParams struct {
	Status string `json:"status"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListEmailEventsByStatus(ctx context.Context, arg ListEmailEventsByStatusParams) ([]EmailEvent, error) {
	rows, err := q.db.QueryContext(ctx, listEmailEventsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailEvent
	for rows.Next() {
		var i EmailEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.RecipientEmail,
			&i.ProviderMessageID,
			&i.Status,
			&i.ErrorText,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmailEventStatus = `-- name: UpdateEmailEventStatus :exec
UPDATE email_events
SET status = ?,
    provider_message_id = ?,
    error_text = ?
WHERE id = ?
`

type UpdateEmailEventStatusParams struct {
	Status            string         `json:"status"`
	ProviderMessageID sql.NullString `json:"provider_message_id"`
	ErrorText         sql.NullString `json:"error_text"`
	ID                string         `json:"id"`
}

func (q *Queries) UpdateEmailEventStatus(ctx context.Context, arg UpdateEmailEventStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateEmailEventStatus,
		arg.Status,
		arg.ProviderMessageID,
		arg.ErrorText,
		arg.ID,
	)
	return err
}
