// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package db

import (
	"context"
	"database/sql"
)

const createFile = `-- name: CreateFile :exec
INSERT INTO files (id, uploader_type, uploader_id, original_filename, storage_key, content_type, size_bytes, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateFileParams struct {
	ID               string         `json:"id"`
	UploaderType     string         `json:"uploader_type"`
	UploaderID       string         `json:"uploader_id"`
	OriginalFilename string         `json:"original_filename"`
	StorageKey       string         `json:"storage_key"`
	ContentType      string         `json:"content_type"`
	SizeBytes        int64          `json:"size_bytes"`
	ExpiresAt        sql.NullString `json:"expires_at"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.ExecContext(ctx, createFile,
		arg.ID,
		arg.UploaderType,
		arg.UploaderID,
		arg.OriginalFilename,
		arg.StorageKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.ExpiresAt,
	)
	return err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE id = ?
`

func (q *Queries) DeleteFile(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFile, id)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, uploader_type, uploader_id, original_filename, storage_key, content_type, size_bytes, expires_at, created_at
FROM files
WHERE id = ?
`

func (q *Queries) GetFileByID(ctx context.Context, id string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UploaderType,
		&i.UploaderID,
		&i.OriginalFilename,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listFilesByUploader = `-- name: ListFilesByUploader :many
SELECT id, uploader_type, uploader_id, original_filename, storage_key, content_type, size_bytes, expires_at, created_at
FROM files
WHERE uploader_type = ? AND uploader_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListFilesByUploaderParams struct {
	UploaderType string `json:"uploader_type"`
	UploaderID   string `json:"uploader_id"`
	Limit        int64  `json:"limit"`
	Offset       int64  `json:"offset"`
}

func (q *Queries) ListFilesByUploader(ctx context.Context, arg ListFilesByUploaderParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByUploader,
		arg.UploaderType,
		arg.UploaderID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UploaderType,
			&i.UploaderID,
			&i.OriginalFilename,
			&i.StorageKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
