// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: magic_links.sql

package db

import (
	"context"
	"database/sql"
)

const consumeMagicLink = `-- name: ConsumeMagicLink :exec
UPDATE magic_links
SET consumed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

func (q *Queries) ConsumeMagicLink(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, consumeMagicLink, id)
	return err
}

const createMagicLink = `-- name: CreateMagicLink :exec
INSERT INTO magic_links (id, client_id, token_hash, expires_at, consumed_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateMagicLinkParams struct {
	ID         string         `json:"id"`
	ClientID   string         `json:"client_id"`
	TokenHash  string         `json:"token_hash"`
	ExpiresAt  string         `json:"expires_at"`
	ConsumedAt sql.NullString `json:"consumed_at"`
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) error {
	_, err := q.db.ExecContext(ctx, createMagicLink,
		arg.ID,
		arg.ClientID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.ConsumedAt,
	)
	return err
}

const deleteExpiredMagicLinks = `-- name: DeleteExpiredMagicLinks :exec
DELETE FROM magic_links
WHERE expires_at < strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

func (q *Queries) DeleteExpiredMagicLinks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredMagicLinks)
	return err
}

const getMagicLinkByTokenHash = `-- name: GetMagicLinkByTokenHash :one
SELECT id, client_id, token_hash, expires_at, consumed_at, created_at
FROM magic_links
WHERE token_hash = ?
`

func (q *Queries) GetMagicLinkByTokenHash(ctx context.Context, tokenHash string) (MagicLink, error) {
	row := q.db.QueryRowContext(ctx, getMagicLinkByTokenHash, tokenHash)
	var i MagicLink
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listMagicLinksByClient = `-- name: ListMagicLinksByClient :many
SELECT id, client_id, token_hash, expires_at, consumed_at, created_at
FROM magic_links
WHERE client_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListMagicLinksByClient(ctx context.Context, clientID string) ([]MagicLink, error) {
	rows, err := q.db.QueryContext(ctx, listMagicLinksByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MagicLink
	for rows.Next() {
		var i MagicLink
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
