// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Client struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	DisplayName  string         `json:"display_name"`
	PasswordHash sql.NullString `json:"password_hash"`
	CanUpload    int64          `json:"can_upload"`
	IsActive     int64          `json:"is_active"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type ClientGroup struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	CreatedByUserID sql.NullString `json:"created_by_user_id"`
	CreatedAt       string         `json:"created_at"`
}

type ClientGroupMember struct {
	ClientGroupID string `json:"client_group_id"`
	ClientID      string `json:"client_id"`
	CreatedAt     string `json:"created_at"`
}

type MagicLink struct {
	ID         string         `json:"id"`
	ClientID   string         `json:"client_id"`
	TokenHash  string         `json:"token_hash"`
	ExpiresAt  string         `json:"expires_at"`
	ConsumedAt sql.NullString `json:"consumed_at"`
	CreatedAt  string         `json:"created_at"`
}

type Role struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Session struct {
	ID        string         `json:"id"`
	ActorType string         `json:"actor_type"`
	ActorID   string         `json:"actor_id"`
	TokenHash string         `json:"token_hash"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
	ExpiresAt string         `json:"expires_at"`
	CreatedAt string         `json:"created_at"`
	RevokedAt sql.NullString `json:"revoked_at"`
}

type User struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	FullName  string `json:"full_name"`
	IsActive  int64  `json:"is_active"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type UserRole struct {
	UserID    string `json:"user_id"`
	RoleID    int64  `json:"role_id"`
	CreatedAt string `json:"created_at"`
}
