// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type AuditLog struct {
	ID           string         `json:"id"`
	ActorType    sql.NullString `json:"actor_type"`
	ActorID      sql.NullString `json:"actor_id"`
	EventType    string         `json:"event_type"`
	EntityType   sql.NullString `json:"entity_type"`
	EntityID     sql.NullString `json:"entity_id"`
	MetadataJson sql.NullString `json:"metadata_json"`
	CreatedAt    string         `json:"created_at"`
}

type Client struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	DisplayName  string         `json:"display_name"`
	PasswordHash sql.NullString `json:"password_hash"`
	CanUpload    int64          `json:"can_upload"`
	IsActive     int64          `json:"is_active"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type ClientGroup struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	CreatedByUserID sql.NullString `json:"created_by_user_id"`
	CreatedAt       string         `json:"created_at"`
}

type ClientGroupMember struct {
	ClientGroupID string `json:"client_group_id"`
	ClientID      string `json:"client_id"`
	CreatedAt     string `json:"created_at"`
}

type ClientUploadPermission struct {
	ID         string `json:"id"`
	OwnerType  string `json:"owner_type"`
	OwnerID    string `json:"owner_id"`
	TargetType string `json:"target_type"`
	TargetID   string `json:"target_id"`
	CreatedAt  string `json:"created_at"`
}

type EmailEvent struct {
	ID                string         `json:"id"`
	EventType         string         `json:"event_type"`
	RecipientEmail    string         `json:"recipient_email"`
	ProviderMessageID sql.NullString `json:"provider_message_id"`
	Status            string         `json:"status"`
	ErrorText         sql.NullString `json:"error_text"`
	PayloadJson       sql.NullString `json:"payload_json"`
	CreatedAt         string         `json:"created_at"`
}

type File struct {
	ID               string         `json:"id"`
	UploaderType     string         `json:"uploader_type"`
	UploaderID       string         `json:"uploader_id"`
	OriginalFilename string         `json:"original_filename"`
	StorageKey       string         `json:"storage_key"`
	ContentType      string         `json:"content_type"`
	SizeBytes        int64          `json:"size_bytes"`
	ExpiresAt        sql.NullString `json:"expires_at"`
	CreatedAt        string         `json:"created_at"`
}

type MagicLink struct {
	ID         string         `json:"id"`
	ClientID   string         `json:"client_id"`
	TokenHash  string         `json:"token_hash"`
	ExpiresAt  string         `json:"expires_at"`
	ConsumedAt sql.NullString `json:"consumed_at"`
	CreatedAt  string         `json:"created_at"`
}

type Role struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Session struct {
	ID        string         `json:"id"`
	ActorType string         `json:"actor_type"`
	ActorID   string         `json:"actor_id"`
	TokenHash string         `json:"token_hash"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
	ExpiresAt string         `json:"expires_at"`
	CreatedAt string         `json:"created_at"`
	RevokedAt sql.NullString `json:"revoked_at"`
}

type Share struct {
	ID           string         `json:"id"`
	FileID       string         `json:"file_id"`
	SharedByType string         `json:"shared_by_type"`
	SharedByID   string         `json:"shared_by_id"`
	TargetType   string         `json:"target_type"`
	TargetID     string         `json:"target_id"`
	Message      sql.NullString `json:"message"`
	CreatedAt    string         `json:"created_at"`
}

type User struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	FullName  string `json:"full_name"`
	IsActive  int64  `json:"is_active"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type UserGroup struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	CreatedByUserID sql.NullString `json:"created_by_user_id"`
	CreatedAt       string         `json:"created_at"`
}

type UserGroupMember struct {
	UserGroupID string `json:"user_group_id"`
	UserID      string `json:"user_id"`
	CreatedAt   string `json:"created_at"`
}

type UserRole struct {
	UserID    string `json:"user_id"`
	RoleID    int64  `json:"role_id"`
	CreatedAt string `json:"created_at"`
}
