// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: phase1_entities.sql

package db

import (
	"context"
	"database/sql"
)

const addUserRole = `-- name: AddUserRole :exec
INSERT INTO user_roles (user_id, role_id)
VALUES (?, ?)
`

type AddUserRoleParams struct {
	UserID string `json:"user_id"`
	RoleID int64  `json:"role_id"`
}

func (q *Queries) AddUserRole(ctx context.Context, arg AddUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, addUserRole, arg.UserID, arg.RoleID)
	return err
}

const addUserToGroup = `-- name: AddUserToGroup :exec
INSERT INTO user_group_members (user_group_id, user_id)
VALUES (?, ?)
`

type AddUserToGroupParams struct {
	UserGroupID string `json:"user_group_id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error {
	_, err := q.db.ExecContext(ctx, addUserToGroup, arg.UserGroupID, arg.UserID)
	return err
}

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (id, actor_type, actor_id, event_type, entity_type, entity_id, metadata_json)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAuditLogParams struct {
	ID           string         `json:"id"`
	ActorType    sql.NullString `json:"actor_type"`
	ActorID      sql.NullString `json:"actor_id"`
	EventType    string         `json:"event_type"`
	EntityType   sql.NullString `json:"entity_type"`
	EntityID     sql.NullString `json:"entity_id"`
	MetadataJson sql.NullString `json:"metadata_json"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog,
		arg.ID,
		arg.ActorType,
		arg.ActorID,
		arg.EventType,
		arg.EntityType,
		arg.EntityID,
		arg.MetadataJson,
	)
	return err
}

const createClientUploadPermission = `-- name: CreateClientUploadPermission :exec
INSERT INTO client_upload_permissions (id, owner_type, owner_id, target_type, target_id)
VALUES (?, ?, ?, ?, ?)
`

type CreateClientUploadPermissionParams struct {
	ID         string `json:"id"`
	OwnerType  string `json:"owner_type"`
	OwnerID    string `json:"owner_id"`
	TargetType string `json:"target_type"`
	TargetID   string `json:"target_id"`
}

func (q *Queries) CreateClientUploadPermission(ctx context.Context, arg CreateClientUploadPermissionParams) error {
	_, err := q.db.ExecContext(ctx, createClientUploadPermission,
		arg.ID,
		arg.OwnerType,
		arg.OwnerID,
		arg.TargetType,
		arg.TargetID,
	)
	return err
}

const createEmailEvent = `-- name: CreateEmailEvent :exec
INSERT INTO email_events (id, event_type, recipient_email, provider_message_id, status, error_text, payload_json)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateEmailEventParams struct {
	ID                string         `json:"id"`
	EventType         string         `json:"event_type"`
	RecipientEmail    string         `json:"recipient_email"`
	ProviderMessageID sql.NullString `json:"provider_message_id"`
	Status            string         `json:"status"`
	ErrorText         sql.NullString `json:"error_text"`
	PayloadJson       sql.NullString `json:"payload_json"`
}

func (q *Queries) CreateEmailEvent(ctx context.Context, arg CreateEmailEventParams) error {
	_, err := q.db.ExecContext(ctx, createEmailEvent,
		arg.ID,
		arg.EventType,
		arg.RecipientEmail,
		arg.ProviderMessageID,
		arg.Status,
		arg.ErrorText,
		arg.PayloadJson,
	)
	return err
}

const createFile = `-- name: CreateFile :exec
INSERT INTO files (id, uploader_type, uploader_id, original_filename, storage_key, content_type, size_bytes, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateFileParams struct {
	ID               string         `json:"id"`
	UploaderType     string         `json:"uploader_type"`
	UploaderID       string         `json:"uploader_id"`
	OriginalFilename string         `json:"original_filename"`
	StorageKey       string         `json:"storage_key"`
	ContentType      string         `json:"content_type"`
	SizeBytes        int64          `json:"size_bytes"`
	ExpiresAt        sql.NullString `json:"expires_at"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.ExecContext(ctx, createFile,
		arg.ID,
		arg.UploaderType,
		arg.UploaderID,
		arg.OriginalFilename,
		arg.StorageKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.ExpiresAt,
	)
	return err
}

const createShare = `-- name: CreateShare :exec
INSERT INTO shares (id, file_id, shared_by_type, shared_by_id, target_type, target_id, message)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateShareParams struct {
	ID           string         `json:"id"`
	FileID       string         `json:"file_id"`
	SharedByType string         `json:"shared_by_type"`
	SharedByID   string         `json:"shared_by_id"`
	TargetType   string         `json:"target_type"`
	TargetID     string         `json:"target_id"`
	Message      sql.NullString `json:"message"`
}

func (q *Queries) CreateShare(ctx context.Context, arg CreateShareParams) error {
	_, err := q.db.ExecContext(ctx, createShare,
		arg.ID,
		arg.FileID,
		arg.SharedByType,
		arg.SharedByID,
		arg.TargetType,
		arg.TargetID,
		arg.Message,
	)
	return err
}

const createUserGroup = `-- name: CreateUserGroup :exec
INSERT INTO user_groups (id, name, created_by_user_id)
VALUES (?, ?, ?)
`

type CreateUserGroupParams struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	CreatedByUserID sql.NullString `json:"created_by_user_id"`
}

func (q *Queries) CreateUserGroup(ctx context.Context, arg CreateUserGroupParams) error {
	_, err := q.db.ExecContext(ctx, createUserGroup, arg.ID, arg.Name, arg.CreatedByUserID)
	return err
}

const deleteClientUploadPermission = `-- name: DeleteClientUploadPermission :exec
DELETE FROM client_upload_permissions
WHERE id = ?
`

func (q *Queries) DeleteClientUploadPermission(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteClientUploadPermission, id)
	return err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE id = ?
`

func (q *Queries) DeleteFile(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFile, id)
	return err
}

const deleteShare = `-- name: DeleteShare :exec
DELETE FROM shares
WHERE id = ?
`

func (q *Queries) DeleteShare(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteShare, id)
	return err
}

const deleteUserGroup = `-- name: DeleteUserGroup :exec
DELETE FROM user_groups
WHERE id = ?
`

func (q *Queries) DeleteUserGroup(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUserGroup, id)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, uploader_type, uploader_id, original_filename, storage_key, content_type, size_bytes, expires_at, created_at
FROM files
WHERE id = ?
`

func (q *Queries) GetFileByID(ctx context.Context, id string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UploaderType,
		&i.UploaderID,
		&i.OriginalFilename,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getShareByID = `-- name: GetShareByID :one
SELECT id, file_id, shared_by_type, shared_by_id, target_type, target_id, message, created_at
FROM shares
WHERE id = ?
`

func (q *Queries) GetShareByID(ctx context.Context, id string) (Share, error) {
	row := q.db.QueryRowContext(ctx, getShareByID, id)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.SharedByType,
		&i.SharedByID,
		&i.TargetType,
		&i.TargetID,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const getUserGroupByID = `-- name: GetUserGroupByID :one
SELECT id, name, created_by_user_id, created_at
FROM user_groups
WHERE id = ?
`

func (q *Queries) GetUserGroupByID(ctx context.Context, id string) (UserGroup, error) {
	row := q.db.QueryRowContext(ctx, getUserGroupByID, id)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogsByActor = `-- name: ListAuditLogsByActor :many
SELECT id, actor_type, actor_id, event_type, entity_type, entity_id, metadata_json, created_at
FROM audit_logs
WHERE actor_type = ? AND actor_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAuditLogsByActorParams struct {
	ActorType sql.NullString `json:"actor_type"`
	ActorID   sql.NullString `json:"actor_id"`
	Limit     int64          `json:"limit"`
	Offset    int64          `json:"offset"`
}

func (q *Queries) ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByActor,
		arg.ActorType,
		arg.ActorID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorType,
			&i.ActorID,
			&i.EventType,
			&i.EntityType,
			&i.EntityID,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByEventType = `-- name: ListAuditLogsByEventType :many
SELECT id, actor_type, actor_id, event_type, entity_type, entity_id, metadata_json, created_at
FROM audit_logs
WHERE event_type = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAuditLogsByEventTypeParams struct {
	EventType string `json:"event_type"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

func (q *Queries) ListAuditLogsByEventType(ctx context.Context, arg ListAuditLogsByEventTypeParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByEventType, arg.EventType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorType,
			&i.ActorID,
			&i.EventType,
			&i.EntityType,
			&i.EntityID,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientUploadPermissionsByOwner = `-- name: ListClientUploadPermissionsByOwner :many
SELECT id, owner_type, owner_id, target_type, target_id, created_at
FROM client_upload_permissions
WHERE owner_type = ? AND owner_id = ?
ORDER BY created_at DESC
`

type ListClientUploadPermissionsByOwnerParams struct {
	OwnerType string `json:"owner_type"`
	OwnerID   string `json:"owner_id"`
}

func (q *Queries) ListClientUploadPermissionsByOwner(ctx context.Context, arg ListClientUploadPermissionsByOwnerParams) ([]ClientUploadPermission, error) {
	rows, err := q.db.QueryContext(ctx, listClientUploadPermissionsByOwner, arg.OwnerType, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientUploadPermission
	for rows.Next() {
		var i ClientUploadPermission
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.OwnerID,
			&i.TargetType,
			&i.TargetID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailEventsByStatus = `-- name: ListEmailEventsByStatus :many
SELECT id, event_type, recipient_email, provider_message_id, status, error_text, payload_json, created_at
FROM email_events
WHERE status = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListEmailEventsByStatusParams struct {
	Status string `json:"status"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListEmailEventsByStatus(ctx context.Context, arg ListEmailEventsByStatusParams) ([]EmailEvent, error) {
	rows, err := q.db.QueryContext(ctx, listEmailEventsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailEvent
	for rows.Next() {
		var i EmailEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.RecipientEmail,
			&i.ProviderMessageID,
			&i.Status,
			&i.ErrorText,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByUploader = `-- name: ListFilesByUploader :many
SELECT id, uploader_type, uploader_id, original_filename, storage_key, content_type, size_bytes, expires_at, created_at
FROM files
WHERE uploader_type = ? AND uploader_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListFilesByUploaderParams struct {
	UploaderType string `json:"uploader_type"`
	UploaderID   string `json:"uploader_id"`
	Limit        int64  `json:"limit"`
	Offset       int64  `json:"offset"`
}

func (q *Queries) ListFilesByUploader(ctx context.Context, arg ListFilesByUploaderParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByUploader,
		arg.UploaderType,
		arg.UploaderID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UploaderType,
			&i.UploaderID,
			&i.OriginalFilename,
			&i.StorageKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupUsers = `-- name: ListGroupUsers :many
SELECT u.id, u.email, u.full_name, u.is_active, u.created_at, u.updated_at
FROM users u
JOIN user_group_members ugm ON ugm.user_id = u.id
WHERE ugm.user_group_id = ?
ORDER BY u.created_at DESC
`

func (q *Queries) ListGroupUsers(ctx context.Context, userGroupID string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listGroupUsers, userGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name
FROM roles
ORDER BY id ASC
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharesByTarget = `-- name: ListSharesByTarget :many
SELECT id, file_id, shared_by_type, shared_by_id, target_type, target_id, message, created_at
FROM shares
WHERE target_type = ? AND target_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListSharesByTargetParams struct {
	TargetType string `json:"target_type"`
	TargetID   string `json:"target_id"`
	Limit      int64  `json:"limit"`
	Offset     int64  `json:"offset"`
}

func (q *Queries) ListSharesByTarget(ctx context.Context, arg ListSharesByTargetParams) ([]Share, error) {
	rows, err := q.db.QueryContext(ctx, listSharesByTarget,
		arg.TargetType,
		arg.TargetID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Share
	for rows.Next() {
		var i Share
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.SharedByType,
			&i.SharedByID,
			&i.TargetType,
			&i.TargetID,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT id, name, created_by_user_id, created_at
FROM user_groups
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListUserGroupsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListUserGroups(ctx context.Context, arg ListUserGroupsParams) ([]UserGroup, error) {
	rows, err := q.db.QueryContext(ctx, listUserGroups, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroup
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT ur.user_id, ur.role_id, ur.created_at
FROM user_roles ur
WHERE ur.user_id = ?
ORDER BY ur.created_at DESC
`

func (q *Queries) ListUserRoles(ctx context.Context, userID string) ([]UserRole, error) {
	rows, err := q.db.QueryContext(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRole
	for rows.Next() {
		var i UserRole
		if err := rows.Scan(&i.UserID, &i.RoleID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromGroup = `-- name: RemoveUserFromGroup :exec
DELETE FROM user_group_members
WHERE user_group_id = ? AND user_id = ?
`

type RemoveUserFromGroupParams struct {
	UserGroupID string `json:"user_group_id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, removeUserFromGroup, arg.UserGroupID, arg.UserID)
	return err
}

const removeUserRole = `-- name: RemoveUserRole :exec
DELETE FROM user_roles
WHERE user_id = ? AND role_id = ?
`

type RemoveUserRoleParams struct {
	UserID string `json:"user_id"`
	RoleID int64  `json:"role_id"`
}

func (q *Queries) RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, removeUserRole, arg.UserID, arg.RoleID)
	return err
}

const updateEmailEventStatus = `-- name: UpdateEmailEventStatus :exec
UPDATE email_events
SET status = ?,
    error_text = ?
WHERE id = ?
`

type UpdateEmailEventStatusParams struct {
	Status    string         `json:"status"`
	ErrorText sql.NullString `json:"error_text"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateEmailEventStatus(ctx context.Context, arg UpdateEmailEventStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateEmailEventStatus, arg.Status, arg.ErrorText, arg.ID)
	return err
}

const updateUserGroup = `-- name: UpdateUserGroup :exec
UPDATE user_groups
SET name = ?
WHERE id = ?
`

type UpdateUserGroupParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateUserGroup(ctx context.Context, arg UpdateUserGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateUserGroup, arg.Name, arg.ID)
	return err
}
