// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddClientToGroup(ctx context.Context, arg AddClientToGroupParams) error
	AddUserRole(ctx context.Context, arg AddUserRoleParams) error
	AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error
	ConsumeMagicLink(ctx context.Context, id string) error
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateClient(ctx context.Context, arg CreateClientParams) error
	CreateClientGroup(ctx context.Context, arg CreateClientGroupParams) error
	CreateClientUploadPermission(ctx context.Context, arg CreateClientUploadPermissionParams) error
	CreateEmailEvent(ctx context.Context, arg CreateEmailEventParams) error
	CreateFile(ctx context.Context, arg CreateFileParams) error
	CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateShare(ctx context.Context, arg CreateShareParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateUserGroup(ctx context.Context, arg CreateUserGroupParams) error
	DeleteClient(ctx context.Context, id string) error
	DeleteClientGroup(ctx context.Context, id string) error
	DeleteClientUploadPermission(ctx context.Context, id string) error
	DeleteExpiredMagicLinks(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteFile(ctx context.Context, id string) error
	DeleteShare(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	DeleteUserGroup(ctx context.Context, id string) error
	GetClientByEmail(ctx context.Context, lower string) (Client, error)
	GetClientByID(ctx context.Context, id string) (Client, error)
	GetClientGroupByID(ctx context.Context, id string) (ClientGroup, error)
	GetFileByID(ctx context.Context, id string) (File, error)
	GetMagicLinkByTokenHash(ctx context.Context, tokenHash string) (MagicLink, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	GetShareByID(ctx context.Context, id string) (Share, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserGroupByID(ctx context.Context, id string) (UserGroup, error)
	ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error)
	ListAuditLogsByEventType(ctx context.Context, arg ListAuditLogsByEventTypeParams) ([]AuditLog, error)
	ListClientGroups(ctx context.Context, arg ListClientGroupsParams) ([]ClientGroup, error)
	ListClientUploadPermissionsByOwner(ctx context.Context, arg ListClientUploadPermissionsByOwnerParams) ([]ClientUploadPermission, error)
	ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error)
	ListEmailEventsByStatus(ctx context.Context, arg ListEmailEventsByStatusParams) ([]EmailEvent, error)
	ListFilesByUploader(ctx context.Context, arg ListFilesByUploaderParams) ([]File, error)
	ListGroupClients(ctx context.Context, clientGroupID string) ([]Client, error)
	ListGroupUsers(ctx context.Context, userGroupID string) ([]ListGroupUsersRow, error)
	ListMagicLinksByClient(ctx context.Context, clientID string) ([]MagicLink, error)
	ListRoleNamesByUserID(ctx context.Context, userID string) ([]string, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListSessionsByActor(ctx context.Context, arg ListSessionsByActorParams) ([]Session, error)
	ListSharesByTarget(ctx context.Context, arg ListSharesByTargetParams) ([]Share, error)
	ListUserGroups(ctx context.Context, arg ListUserGroupsParams) ([]UserGroup, error)
	ListUserRoles(ctx context.Context, userID string) ([]UserRole, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RemoveClientFromGroup(ctx context.Context, arg RemoveClientFromGroupParams) error
	RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error
	RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error
	RevokeSessionByID(ctx context.Context, id string) error
	UpdateClient(ctx context.Context, arg UpdateClientParams) error
	UpdateClientGroup(ctx context.Context, arg UpdateClientGroupParams) error
	UpdateEmailEventStatus(ctx context.Context, arg UpdateEmailEventStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserGroup(ctx context.Context, arg UpdateUserGroupParams) error
}

var _ Querier = (*Queries)(nil)
