// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	AddClientToGroup(ctx context.Context, arg AddClientToGroupParams) error
	ConsumeMagicLink(ctx context.Context, id string) error
	CreateClient(ctx context.Context, arg CreateClientParams) error
	CreateClientGroup(ctx context.Context, arg CreateClientGroupParams) error
	CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteClient(ctx context.Context, id string) error
	DeleteClientGroup(ctx context.Context, id string) error
	DeleteExpiredMagicLinks(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteUser(ctx context.Context, id string) error
	GetClientByEmail(ctx context.Context, email string) (Client, error)
	GetClientByID(ctx context.Context, id string) (Client, error)
	GetClientGroupByID(ctx context.Context, id string) (ClientGroup, error)
	GetMagicLinkByTokenHash(ctx context.Context, tokenHash string) (MagicLink, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	ListClientGroups(ctx context.Context, arg ListClientGroupsParams) ([]ClientGroup, error)
	ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error)
	ListGroupClients(ctx context.Context, clientGroupID string) ([]Client, error)
	ListMagicLinksByClient(ctx context.Context, clientID string) ([]MagicLink, error)
	ListSessionsByActor(ctx context.Context, arg ListSessionsByActorParams) ([]Session, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RemoveClientFromGroup(ctx context.Context, arg RemoveClientFromGroupParams) error
	RevokeSessionByID(ctx context.Context, id string) error
	UpdateClient(ctx context.Context, arg UpdateClientParams) error
	UpdateClientGroup(ctx context.Context, arg UpdateClientGroupParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
