// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, actor_type, actor_id, token_hash, ip_address, user_agent, expires_at, revoked_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID        string         `json:"id"`
	ActorType string         `json:"actor_type"`
	ActorID   string         `json:"actor_id"`
	TokenHash string         `json:"token_hash"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
	ExpiresAt string         `json:"expires_at"`
	RevokedAt sql.NullString `json:"revoked_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.ActorType,
		arg.ActorID,
		arg.TokenHash,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
		arg.RevokedAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, actor_type, actor_id, token_hash, ip_address, user_agent, expires_at, created_at, revoked_at
FROM sessions
WHERE token_hash = ?
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ActorType,
		&i.ActorID,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listSessionsByActor = `-- name: ListSessionsByActor :many
SELECT id, actor_type, actor_id, token_hash, ip_address, user_agent, expires_at, created_at, revoked_at
FROM sessions
WHERE actor_type = ? AND actor_id = ?
ORDER BY created_at DESC
`

type ListSessionsByActorParams struct {
	ActorType string `json:"actor_type"`
	ActorID   string `json:"actor_id"`
}

func (q *Queries) ListSessionsByActor(ctx context.Context, arg ListSessionsByActorParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByActor, arg.ActorType, arg.ActorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ActorType,
			&i.ActorID,
			&i.TokenHash,
			&i.IpAddress,
			&i.UserAgent,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSessionByID = `-- name: RevokeSessionByID :exec
UPDATE sessions
SET revoked_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

func (q *Queries) RevokeSessionByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeSessionByID, id)
	return err
}
