// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: share_downloads.sql

package db

import (
	"context"
)

const fileHasAnyClientDownload = `-- name: FileHasAnyClientDownload :one
SELECT EXISTS (
  SELECT 1
  FROM shares s
  JOIN share_downloads sd ON sd.share_id = s.id
  WHERE s.file_id = ?
)
`

func (q *Queries) FileHasAnyClientDownload(ctx context.Context, fileID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, fileHasAnyClientDownload, fileID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const recordShareDownload = `-- name: RecordShareDownload :exec
INSERT INTO share_downloads (id, share_id, client_id)
VALUES (?, ?, ?)
ON CONFLICT(share_id, client_id) DO UPDATE SET
  last_downloaded_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
  download_count = share_downloads.download_count + 1,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

type RecordShareDownloadParams struct {
	ID       string `json:"id"`
	ShareID  string `json:"share_id"`
	ClientID string `json:"client_id"`
}

func (q *Queries) RecordShareDownload(ctx context.Context, arg RecordShareDownloadParams) error {
	_, err := q.db.ExecContext(ctx, recordShareDownload, arg.ID, arg.ShareID, arg.ClientID)
	return err
}
