// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package db

import (
	"context"
	"database/sql"
)

const createShare = `-- name: CreateShare :exec
INSERT INTO shares (id, file_id, shared_by_type, shared_by_id, target_type, target_id, message)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateShareParams struct {
	ID           string         `json:"id"`
	FileID       string         `json:"file_id"`
	SharedByType string         `json:"shared_by_type"`
	SharedByID   string         `json:"shared_by_id"`
	TargetType   string         `json:"target_type"`
	TargetID     string         `json:"target_id"`
	Message      sql.NullString `json:"message"`
}

func (q *Queries) CreateShare(ctx context.Context, arg CreateShareParams) error {
	_, err := q.db.ExecContext(ctx, createShare,
		arg.ID,
		arg.FileID,
		arg.SharedByType,
		arg.SharedByID,
		arg.TargetType,
		arg.TargetID,
		arg.Message,
	)
	return err
}

const deleteShare = `-- name: DeleteShare :exec
DELETE FROM shares
WHERE id = ?
`

func (q *Queries) DeleteShare(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteShare, id)
	return err
}

const getShareByID = `-- name: GetShareByID :one
SELECT id, file_id, shared_by_type, shared_by_id, target_type, target_id, message, created_at
FROM shares
WHERE id = ?
`

func (q *Queries) GetShareByID(ctx context.Context, id string) (Share, error) {
	row := q.db.QueryRowContext(ctx, getShareByID, id)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.SharedByType,
		&i.SharedByID,
		&i.TargetType,
		&i.TargetID,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const listSharesByTarget = `-- name: ListSharesByTarget :many
SELECT id, file_id, shared_by_type, shared_by_id, target_type, target_id, message, created_at
FROM shares
WHERE target_type = ? AND target_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListSharesByTargetParams struct {
	TargetType string `json:"target_type"`
	TargetID   string `json:"target_id"`
	Limit      int64  `json:"limit"`
	Offset     int64  `json:"offset"`
}

func (q *Queries) ListSharesByTarget(ctx context.Context, arg ListSharesByTargetParams) ([]Share, error) {
	rows, err := q.db.QueryContext(ctx, listSharesByTarget,
		arg.TargetType,
		arg.TargetID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Share
	for rows.Next() {
		var i Share
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.SharedByType,
			&i.SharedByID,
			&i.TargetType,
			&i.TargetID,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
