// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: share_downloads.sql

package db

import (
	"context"
)

const fileHasAnyClientDownload = `-- name: FileHasAnyClientDownload :one
SELECT EXISTS (
  SELECT 1
  FROM shares s
  JOIN share_downloads sd ON sd.share_id = s.id
  WHERE s.file_id = ?
)
`

func (q *Queries) FileHasAnyClientDownload(ctx context.Context, fileID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, fileHasAnyClientDownload, fileID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFileViewHistory = `-- name: ListFileViewHistory :many
SELECT
  c.display_name AS viewer_name,
  sd.first_downloaded_at,
  sd.last_downloaded_at,
  sd.download_count
FROM share_downloads sd
JOIN shares s ON s.id = sd.share_id
JOIN clients c ON c.id = sd.client_id
WHERE s.file_id = ?
ORDER BY sd.last_downloaded_at DESC
`

type ListFileViewHistoryRow struct {
	ViewerName        string `json:"viewer_name"`
	FirstDownloadedAt string `json:"first_downloaded_at"`
	LastDownloadedAt  string `json:"last_downloaded_at"`
	DownloadCount     int64  `json:"download_count"`
}

func (q *Queries) ListFileViewHistory(ctx context.Context, fileID string) ([]ListFileViewHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listFileViewHistory, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFileViewHistoryRow
	for rows.Next() {
		var i ListFileViewHistoryRow
		if err := rows.Scan(
			&i.ViewerName,
			&i.FirstDownloadedAt,
			&i.LastDownloadedAt,
			&i.DownloadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShareViewHistory = `-- name: ListShareViewHistory :many
SELECT
  c.display_name AS viewer_name,
  sd.first_downloaded_at,
  sd.last_downloaded_at,
  sd.download_count
FROM share_downloads sd
JOIN clients c ON c.id = sd.client_id
WHERE sd.share_id = ?
ORDER BY sd.last_downloaded_at DESC
`

type ListShareViewHistoryRow struct {
	ViewerName        string `json:"viewer_name"`
	FirstDownloadedAt string `json:"first_downloaded_at"`
	LastDownloadedAt  string `json:"last_downloaded_at"`
	DownloadCount     int64  `json:"download_count"`
}

func (q *Queries) ListShareViewHistory(ctx context.Context, shareID string) ([]ListShareViewHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listShareViewHistory, shareID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShareViewHistoryRow
	for rows.Next() {
		var i ListShareViewHistoryRow
		if err := rows.Scan(
			&i.ViewerName,
			&i.FirstDownloadedAt,
			&i.LastDownloadedAt,
			&i.DownloadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordShareDownload = `-- name: RecordShareDownload :exec
INSERT INTO share_downloads (id, share_id, client_id)
VALUES (?, ?, ?)
ON CONFLICT(share_id, client_id) DO UPDATE SET
  last_downloaded_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
  download_count = share_downloads.download_count + 1,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

type RecordShareDownloadParams struct {
	ID       string `json:"id"`
	ShareID  string `json:"share_id"`
	ClientID string `json:"client_id"`
}

func (q *Queries) RecordShareDownload(ctx context.Context, arg RecordShareDownloadParams) error {
	_, err := q.db.ExecContext(ctx, recordShareDownload, arg.ID, arg.ShareID, arg.ClientID)
	return err
}

const shareHasAnyDownload = `-- name: ShareHasAnyDownload :one
SELECT EXISTS (
  SELECT 1
  FROM share_downloads sd
  WHERE sd.share_id = ?
)
`

func (q *Queries) ShareHasAnyDownload(ctx context.Context, shareID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, shareHasAnyDownload, shareID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
