// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_groups.sql

package db

import (
	"context"
	"database/sql"
)

const addUserToGroup = `-- name: AddUserToGroup :exec
INSERT INTO user_group_members (user_group_id, user_id)
VALUES (?, ?)
`

type AddUserToGroupParams struct {
	UserGroupID string `json:"user_group_id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error {
	_, err := q.db.ExecContext(ctx, addUserToGroup, arg.UserGroupID, arg.UserID)
	return err
}

const createUserGroup = `-- name: CreateUserGroup :exec
INSERT INTO user_groups (id, name, created_by_user_id)
VALUES (?, ?, ?)
`

type CreateUserGroupParams struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	CreatedByUserID sql.NullString `json:"created_by_user_id"`
}

func (q *Queries) CreateUserGroup(ctx context.Context, arg CreateUserGroupParams) error {
	_, err := q.db.ExecContext(ctx, createUserGroup, arg.ID, arg.Name, arg.CreatedByUserID)
	return err
}

const deleteUserGroup = `-- name: DeleteUserGroup :exec
DELETE FROM user_groups
WHERE id = ?
`

func (q *Queries) DeleteUserGroup(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUserGroup, id)
	return err
}

const getUserGroupByID = `-- name: GetUserGroupByID :one
SELECT id, name, created_by_user_id, created_at
FROM user_groups
WHERE id = ?
`

func (q *Queries) GetUserGroupByID(ctx context.Context, id string) (UserGroup, error) {
	row := q.db.QueryRowContext(ctx, getUserGroupByID, id)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listGroupUsers = `-- name: ListGroupUsers :many
SELECT u.id, u.email, u.full_name, u.is_active, u.created_at, u.updated_at
FROM users u
JOIN user_group_members ugm ON ugm.user_id = u.id
WHERE ugm.user_group_id = ?
ORDER BY u.created_at DESC
`

func (q *Queries) ListGroupUsers(ctx context.Context, userGroupID string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listGroupUsers, userGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT id, name, created_by_user_id, created_at
FROM user_groups
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListUserGroupsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListUserGroups(ctx context.Context, arg ListUserGroupsParams) ([]UserGroup, error) {
	rows, err := q.db.QueryContext(ctx, listUserGroups, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroup
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromGroup = `-- name: RemoveUserFromGroup :exec
DELETE FROM user_group_members
WHERE user_group_id = ? AND user_id = ?
`

type RemoveUserFromGroupParams struct {
	UserGroupID string `json:"user_group_id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, removeUserFromGroup, arg.UserGroupID, arg.UserID)
	return err
}

const updateUserGroup = `-- name: UpdateUserGroup :exec
UPDATE user_groups
SET name = ?
WHERE id = ?
`

type UpdateUserGroupParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateUserGroup(ctx context.Context, arg UpdateUserGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateUserGroup, arg.Name, arg.ID)
	return err
}
